from __future__ import annotations

import io
import json
import re
from datetime import date
from pathlib import Path
from typing import Any

from flask import Flask, jsonify, render_template, request
from pypdf import PdfReader, PdfWriter
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

app = Flask(__name__)

DATA_DIR = Path("data")
OUTPUT_DIR = Path("outputs")
MEMORY_FILE = DATA_DIR / "vendor_memory.json"

FUND_CODES = {
    "640800": "COMPUTER SUPPLIES AND MATERIALS",
    "645500": "MAINTENANCE AND SHOP SUPPLIES AND MATERIALS",
    "645900": "COPING SERVICES",
    "646000": "OFFICE SUPPLIES AND MATERIALS",
    "675700": "MINOR MACHINERY AND EQUIPMENT",
    "677400": "COMPUTERS AND MINOR COMPUTER ACCESSORIES",
    "677600": "COMPUTER SOFTWARE (Personal)",
    "687400": "COMPUTERS",
    "686500": "M&R REIMBURSABLES",
    "687600": "COMPUTER SOFTWARE (Enterprise)",
    "688600": "TELEPHONE MAINTENANCE",
    "690100": "INTERDEPARTMENTAL SERVICES EXPENSE",
    "691600": "CONTRACT WORK",
    "691700": "CONTINUING EDUCATION/TRAINING EXPENSES",
    "693600": "FREIGHT EXPRESS AND POSTAGE",
    "694300": "RESERVE - MINOR ACQUISITION BETTERMENTS",
    "696500": "PARKING EXPENSE",
    "698040": "WEBEX",
    "697300": "SERVICES PURCHASED",
    "698205": "VOIP ANALOG",
    "698206": "VOIP DIGITAL",
    "698230": "CELLULAR SERVICE",
    "698600": "TRAVEL AND LIVING EXPENSE - DOMESTIC",
}

KEYWORD_SUGGESTIONS = {
    "software": "687600",
    "license": "687600",
    "office": "646000",
    "supplies": "646000",
    "computer": "677400",
    "laptop": "687400",
    "phone": "698230",
    "cell": "698230",
    "travel": "698600",
    "hotel": "698600",
    "flight": "698600",
    "parking": "696500",
    "postage": "693600",
    "shipping": "693600",
    "training": "691700",
    "maintenance": "645500",
    "webex": "698040",
}


def ensure_dirs() -> None:
    DATA_DIR.mkdir(exist_ok=True)
    OUTPUT_DIR.mkdir(exist_ok=True)


def load_memory() -> dict[str, Any]:
    ensure_dirs()
    if not MEMORY_FILE.exists():
        return {"user_name": "", "vendors": {}}

    with MEMORY_FILE.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def save_memory(memory: dict[str, Any]) -> None:
    ensure_dirs()
    with MEMORY_FILE.open("w", encoding="utf-8") as fh:
        json.dump(memory, fh, indent=2)


def sanitize_filename(value: str) -> str:
    cleaned = re.sub(r"[\\/:*?\"<>|]", "", value).strip()
    return re.sub(r"\s+", " ", cleaned)


def dollars_and_cents(amount: str) -> str:
    normalized = amount.replace("$", "").replace(",", "").strip()
    if not normalized:
        return "00-00"

    dollars, _, cents = f"{float(normalized):.2f}".partition(".")
    return f"{int(dollars):02d}-{cents}"


def suggest_fund_code(vendor: str, purchase: str, description: str, memory: dict[str, Any]) -> str | None:
    vendor_key = vendor.strip().lower()
    vendor_data = memory.get("vendors", {}).get(vendor_key)
    if vendor_data and vendor_data.get("fund_code"):
        return vendor_data["fund_code"]

    search_blob = f"{vendor} {purchase} {description}".lower()
    for keyword, code in KEYWORD_SUGGESTIONS.items():
        if keyword in search_blob:
            return code
    return None


def create_cover_page(payload: dict[str, str], preparer_name: str) -> io.BytesIO:
    packet = io.BytesIO()
    can = canvas.Canvas(packet, pagesize=letter)
    can.setFont("Helvetica-Bold", 18)
    can.drawString(72, 740, "Receipt Cover Page")

    can.setFont("Helvetica", 11)
    lines = [
        f"Prepared By: {preparer_name}",
        f"Vendor: {payload['vendor']}",
        f"Date: {payload['receipt_date']}",
        f"Amount: ${payload['amount']}",
        f"Short Description: {payload['short_description']}",
        f"Project: {payload['project']}",
        f"Purchase: {payload['purchase']}",
        f"Fund Code: {payload['fund_code']} - {FUND_CODES.get(payload['fund_code'], 'Unknown')}",
        "",
        "Generated by Receipt Processor",
    ]

    y = 700
    for line in lines:
        can.drawString(72, y, line)
        y -= 24

    can.showPage()
    can.save()
    packet.seek(0)
    return packet


@app.get("/")
def index():
    memory = load_memory()
    return render_template(
        "index.html",
        fund_codes=FUND_CODES,
        remembered_name=memory.get("user_name", ""),
    )


@app.get("/memory")
def vendor_memory():
    vendor = request.args.get("vendor", "").strip().lower()
    memory = load_memory()
    vendor_data = memory.get("vendors", {}).get(vendor, {})
    return jsonify(vendor_data)


@app.post("/suggest-fund-code")
def suggest_code():
    payload = request.json or {}
    memory = load_memory()
    code = suggest_fund_code(
        payload.get("vendor", ""),
        payload.get("purchase", ""),
        payload.get("short_description", ""),
        memory,
    )
    return jsonify({"fund_code": code, "label": FUND_CODES.get(code, "") if code else ""})


@app.post("/process")
def process_receipts():
    memory = load_memory()
    files = request.files.getlist("receipts")
    meta_raw = request.form.get("metadata", "[]")
    output_subdir = sanitize_filename(request.form.get("output_subdir", "processed"))
    preparer_name = request.form.get("preparer_name", "").strip()

    metadata = json.loads(meta_raw)
    target_dir = OUTPUT_DIR / output_subdir
    target_dir.mkdir(parents=True, exist_ok=True)

    memory["user_name"] = preparer_name

    created_files = []
    for idx, uploaded in enumerate(files):
        info = metadata[idx]
        info["fund_code"] = info.get("fund_code") or suggest_fund_code(
            info.get("vendor", ""),
            info.get("purchase", ""),
            info.get("short_description", ""),
            memory,
        ) or ""

        vendor_key = info["vendor"].strip().lower()
        memory.setdefault("vendors", {})[vendor_key] = {
            "vendor": info["vendor"],
            "fund_code": info["fund_code"],
            "project": info.get("project", ""),
            "purchase": info.get("purchase", ""),
        }

        file_name = sanitize_filename(
            f"{info['vendor']} - {dollars_and_cents(info['amount'])} - {info['receipt_date']} - {info['short_description']}.pdf"
        )
        destination = target_dir / file_name

        cover_pdf = create_cover_page(info, preparer_name)

        writer = PdfWriter()
        cover_reader = PdfReader(cover_pdf)
        writer.add_page(cover_reader.pages[0])

        original_reader = PdfReader(uploaded.stream)
        for page in original_reader.pages:
            writer.add_page(page)

        with destination.open("wb") as out_fh:
            writer.write(out_fh)

        created_files.append(str(destination))

    save_memory(memory)
    return jsonify({"created_files": created_files})


if __name__ == "__main__":
    app.run(debug=True)
